name: hash_link
description: "Hash Link - Criptografia"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  encrypt: ^5.0.0
  pointycastle: ^3.9.1
  file_picker: ^6.1.1
  crypto: ^3.0.3
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  universal_html: ^2.2.4
  path_provider: ^2.1.5
  file_selector: ^1.0.3
  path: ^1.9.0
  window_manager: ^0.4.3
  archive: ^3.6.1
  page_transition: ^2.1.0
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  pdfx: ^2.8.0
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/icon.png
  
flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  web:
    generate: true
    image_path: "assets/images/icon.png"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 1024

license: MIT
